import Foundation

/// Loads the presidential summary data generated by the GenerateAssets tool.
enum PresidentsRepository {
    static func loadAll() -> [President] {
        guard let url = Bundle.main.url(forResource: "Presidents", withExtension: "json") else {
            assertionFailure("Presidents.json missing from bundle")
            return []
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode([President].self, from: data).sorted { $0.order < $1.order }
        } catch {
            assertionFailure("Failed to decode Presidents.json: \(error)")
            return []
        }
    }
}
