import Foundation

/// Loads the head-of-state summary data generated by the GenerateAssets tool.
enum HOSRepository {
    static func loadAll() -> [HOS] {
        guard let url = Bundle.main.url(forResource: "HOS", withExtension: "json") else {
            assertionFailure("HOS.json missing from bundle")
            return []
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode([HOS].self, from: data).sorted { $0.order < $1.order }
        } catch {
            assertionFailure("Failed to decode HOS.json: \(error)")
            return []
        }
    }
}
